/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "proxy_constants.h"

namespace FinagleRegistryProxy {

const proxyConstants g_proxy_constants;

proxyConstants::proxyConstants() {
}

} // namespace

