// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.
#include <sstream>
#include <iostream>   // std::cout
#include <string>     // std::string, std::to_string

#include "RegistryProxy.h"
#include <protocol/TBinaryProtocol.h>
#include <server/TSimpleServer.h>
#include <transport/TServerSocket.h>
#include <transport/TBufferTransports.h>

using namespace std;
using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace ::FinagleRegistryProxy;

class RegistryProxyHandler: virtual public RegistryProxyIf {
public:
	RegistryProxyHandler() {
		// Your initialization goes here
	}

	void get(std::string& _return, const std::string& serviceName) {
		stringstream ss;
		ss << (time(0) / 1000);

		_return = "test get " + ss.str();
		cout << _return << endl;
	}

	void remove(std::string& _return, const std::string& serviceName, const std::string& host, const int32_t port) {
		// Your implementation goes here
		printf("remove\n");
		_return = "test remove";
	}
	void dump(std::string& _return) {
		_return = "";
	}
	void reset(std::string& _return) {
		// Your implementation goes here
		printf("reset\n");
	}

	int32_t status() {
		// Your implementation goes here
		printf("status\n");
	}

};
